name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Specify the desired Python version

      - name: Install FFmpeg
        run: |
          RUN apt-get update && apt-get install git -y
          RUN pip3 install -r requirements.txt
          RUN pip3 install "git+https://github.com/openai/whisper.git" 
          RUN apt-get install -y ffmpeg

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlit streamlit-chat 
          pip install farm-haystack 
          pip install 'farm-haystack[faiss]'
          pip install tiktoken
          pip install -r requirements.txt  # Replace with the actual name of your requirements file

      - name: Set up secret file
      env:
        DEBUG_PASSWORD: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo $DEBUG_PASSWORD >> secrets.txt
        echo $DEBUG_SECRET_KEY >> secrets.txt

      - name: Deploy Streamlit App
        run: |
          streamlit run app.py  # Replace with the actual name of your Streamlit app file
